### ISSUE TITLE
[Feature] MaterialDesign

### ISSUE THREAD

**Issue by siegerx3** [jammin411/MatchmakingMonitor#11]
Update the ui to MaterialDesign

**Comment by danielvistisen** [comment]
Meterial design is a google thing?

Fluent design is what Microsoft recommend for their platform now.

http://fluent.microsoft.com/

My suggestion would be to follow that design pattern instead.

**Comment by siegerx3** [comment]
It's Material Design because the wowreplays.com page used it. True, now that it's not there anymore we can consider another modern design pattern.

**Comment by siegerx3** [comment]
Doesn't seem like Fluent Design is available for WPF

**Comment by siegerx3** [comment]
#34
