### ISSUE TITLE
[Bug] Customizing values not saved after app restart

### ISSUE THREAD

**Issue by siegerx3** [jammin411/MatchmakingMonitor#17]
When manually chaning any of the limit values, they will be overwritten by the remote values after restarting the app.

**Comment by siegerx3** [comment]
I will probably add an option in the settings.

"Automatically resync values with every startup" yes/no

**Comment by danielvistisen** [comment]
If set to yes. You should probably disable the fields. Make it more intuitive to the user whats going?

**Comment by siegerx3** [comment]
Good idea. Will do that.
