### ISSUE TITLE
[Feature] Automatic app update

### ISSUE THREAD

**Issue by danielvistisen** [jammin411/MatchmakingMonitor#19]
Since atleast the version from aslain mod pack is a clickonce. Setting it to auto update would be nice. That way I don't have to worry about having the latest version.

Just a solution poposal. How it done is not really important. But its probably the easiest way of doing it.

**Comment by siegerx3** [comment]
The version from aslain has no auto update or anything like that. It's just one specific version before i added the "new version available prompt"
There was never such thing as an auto update implemented.

Also by having ppl download it from the website manually i can track it with google analytics though...
But i'll see.

**Comment by danielvistisen** [comment]
Clickonce is build in Visual studio. It the default way of creating an installation when you press "publish" on your WPF project. This setup can be setup to look at a specific URL for updates. If a different version is found it will install it before opening the app. This is regardless whether its a newer version or an older (in case you want to rollback to an older version). 

The .application file is just an clickonce xml file. Containing basic information like where to check for updates. Since the one is aslian didn't contain this information auto update isn't enabled for that clickonce installation.

You might still be able to track it with google analytics as it still performs an request to the site. Note that anti bot systems might block this request so perhaps google analytics also will ignore it by default? Isn't it more relevant to put analytics inside the app anyway? Seeing how often its used for how long and by how many unique users? I think google analytics has a SDK for .NET not sure though as I mainly use HockeyApp/Application insight for this.

I personally dislike the update promt. But thats just my opinion.

**Comment by siegerx3** [comment]
Oh i didn't know that.
Sounds interesting.

I didn't know aslain added this clickonce stuff. I just provided (well, jammin did) with the zip folder.

Since the request would go directly to the server and not over my website GA wouldn't track it but yeah i thought about adding analytics also to the .net app. For now i'm just curious how many visitors i have on the page etc.

I didn't think about automatic updates because i felt like i didn't want to force ppl to update. But it could be a prompt asking for downloading&installing the new version. 

I don't use the publish tho. I just use a customized release build with some postbuild tasks to remove unused dlls.

**Comment by danielvistisen** [comment]
Request will go where ever you want it to go. When creating a clickonce application for web hosting it will create a "small website" for you. (index.html file I think) So you will need a dedicated domain/subdomain which can host this site. When opening the app it knows that this domain will have an .application file that it will compare with to see if update/downgrade is needed and if so install before the app is opened (No next clicking or anything else. Why its called clickonce.) Should you decide to check this out let me know if you need any assistant. I'll gladly help.

**Comment by siegerx3** [comment]
I'd still say i would want to let the user decide what to do so they are aware of installing a new version, but i will check it out!

**Comment by danielvistisen** [comment]
Here is my thoughts on the ”let the user decide whether to update or not”. And yes, I’m trying to convince you not to go with that approach. :-)

Let’s start with the UX. I want to use the app so I open it. A dialog appears telling me an update is out. So, before I can start using the app I need to make a decision. Not why I as a user started the app. Lets go with the “No” to update for now. I see two options here.
1.	I get prompted next time I open again. Which just makes it even more annoying for every time.
2.	I don’t and now I need to figure how to get the update. This could be solved with a link inside the app. But if that’s there why did I need a prompt in the first place. If the link is there there’s an update?
Now I want to update. Again, this process is harder than it needs to be. I need to download, once this is completed I need to install it as well. Perhaps even unzip it and after delete the installation file to keep my download folder nice and clean. There are of course solutions for that as well.

Dev perspective:
If you let your users decide you should support backwards at a much larger scale. Every time you change something in your web api you need to be sure it supports all previous versions. So you either need to create versions of your api to match or only expand your interface. Never delete or rename. And if any 3rd party (E.g. warships.today) changes something your screwed. Then is no longer a choice to update for the user for the app won’t work if it isn’t updated.

Again, how you solve this doesn’t really matter to me. Clickonce is just a suggestion as its build in and everything is done for you. No code needed inside the app. But as a user I really prefer my app’s to auto update. I'm really lazy. :-).

**Comment by siegerx3** [comment]
> I don’t and now I need to figure how to get the update 
Good points beside this one^^ When you click yes it opens the download page ;) Since that's how it is atm.

As i said, i'll look into the clickonce stuff.
Maybe i also like the current way because i like my web notifications when a new version is out x)

But yeah as i said, good points. Gonna fix the bugs later today and see what i'll do about the update stuff.

**Comment by siegerx3** [comment]
Oh but i think if i implement an auto update function, i will still make it optional (active by default) in case there is a new version and it doesn't work for some ppl. they can still use the older version until the bug is fixed

**Comment by siegerx3** [comment]
Worked with all my test cases. We will see if it will work with the next version being released.
If the automatic update is disabled it's the same as before. Dialog linking to the download page.
