### ISSUE TITLE
Certain settings.json file configurations cause crash on startup

### ISSUE THREAD

**Issue by dziban303** [jammin411/MatchmakingMonitor#25]
For the last several versions (since 1.0.5.0 at least):

After initial installation and path configuration, the program works fine. Eventually, after a few days, the program no longer starts. No window appears when launching the program. In Task Manager, the process shows up, but then exits. There is no error message. No changes were made to the `settings.json` file prior to the problem beginning.

When this happens, deleting the `settings.json` file allows the program to start again, although configuration must obviously be done once more. In my case, the _only_ configuration done is changing the game path. No other settings are changed from the default values.

Upon examining the json files, nothing is obviously amiss, although some values have changed and the token is different. I don't know why any settings change at all, because as I mentioned, I don't change anything from the defaults besides the install directory on first run, and I don't change anything after that.

I'm using v1.0.6.1, downloaded from here: [https://monitor.pepespub.de/download](https://monitor.pepespub.de/download). Windows 10 Pro version 1703 (build 15063.413).

Attached are an example of a settings.json file that prevents the program from starting, and one that works. 

[MatchmakingMonitor settings.json examples.zip](https://github.com/jammin411/MatchmakingMonitor/files/1202003/MatchmakingMonitor.settings.json.examples.zip)

I would be happy to help with troubleshooting further.

**Comment by danielvistisen** [comment]
@dziban303  For "fix" you can try Shift+Right click on the Icon in taskbar and select Maximize. Had similar issue. (Faster than deleting file every time if it works)

**Comment by danielvistisen** [comment]
Oh its not the same problem. After some testing this dosn't solve it. However, to avoid this problem. Never close the app when its minimized. 

If you want to keep your settings: Change this in the settings file: 
"windowState":1 
to either 
"windowState":0 
for normal window or
"windowState":2 
for maximized. Works after.

**Comment by dziban303** [comment]
I definitely wasn't closing the app while it was minimized.

Anyway I created a batch file to copy over the known-good config and then launch the app.

**Comment by dziban303** [comment]
New issue. Since update, about half the players are showing up without stats, says "tier 0".

http://i.imgur.com/XUpnPip.png

**Comment by siegerx3** [comment]
Ok i'm seeing multiple issues here^^
One being, when closing in minimized mode it should NOT set the window state.
Then the two different config files, one working, one not.
And the problem with the new update.
I will seperate them and close this one

**Comment by siegerx3** [comment]
#26 #27 #28
