### ISSUE TITLE
[Bug] Update 0.6.9.0 breaks statistics 

### ISSUE THREAD

**Issue by siegerx3** [jammin411/MatchmakingMonitor#26]
> New issue. Since update, about half the players are showing up without stats, says "tier 0". 
> http://i.imgur.com/XUpnPip.png - @dziban303

**Comment by siegerx3** [comment]
@dziban303 Would be great if you could provide me with one of your tempArenaInfo.json files where it breaks like in the image

**Comment by siegerx3** [comment]
#25

**Comment by ArnoHeid** [comment]
@siegerx3 
Here is my tempArenaInfo.json with the same error.
[tempArenaInfo.json.txt](https://github.com/jammin411/MatchmakingMonitor/files/1216067/tempArenaInfo.json.txt)

**Comment by siegerx3** [comment]
Fixed it already :) Had nothing to do with the stats themselves
