### ISSUE TITLE
Auto-update fails

### ISSUE THREAD

**Issue by dziban303** [jammin411/MatchmakingMonitor#30]
Hi @siegerx3 -

Auto-update, after completing the download, fails with the following message:

> An error occured when trying to update the app. Try disabling automatic update 
> and download the latest version manually.
![image](https://user-images.githubusercontent.com/7931765/29198224-93dd2492-7e07-11e7-955a-bac136fff8c5.png)

It's actually never worked before since the feature was added, but I never bothered to report it before. I have tried running the app as an administrator, which makes no difference.

**Comment by siegerx3** [comment]
@dziban303 
You've got any information from the 
> log.txt
?

**Comment by dziban303** [comment]
Here it is. 

8/10/2017 20:04:42 - Info - Checking for match in path C:\World_of_Warships\replays\tempArenaInfo.json
**8/10/2017 20:04:46 - Error - Error during automatic app update - The process cannot access the file 'C:\World_of_Warships\res_mods\MatchmakingMonitor-1.0.6.1\bin\EngineIoClientDotNet.dll' because it is being used by another process.**
8/10/2017 20:11:03 - Info - Checking for match in path C:\World_of_Warships\replays\tempArenaInfo.json
**8/10/2017 20:11:06 - Error - Error during automatic app update - The process cannot access the file 'C:\World_of_Warships\res_mods\MatchmakingMonitor-1.0.6.1\bin\EngineIoClientDotNet.dll' because it is being used by another process.**

**Comment by dziban303** [comment]
Hey, I see you've dropped 1.0.7.1 which disables automatic update.

Until you find a fix, how about either implementing a popup alerting the user to a new update (this may already be the case), or better yet, have the program download the zip file from the website and place it in the same directory. That would make it easy for the user to just unzip the new version via Explorer.

**Comment by siegerx3** [comment]
It already checks for a new version and there is a popup ;)
That's what it basically did just i also extracted the zip.

But sure i could reenable just the zip download without unpacking it.
