### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by BunniosAU** [jammin411/MatchmakingMonitor#31]
The app started crashing on startup on Tuesday 15th August. It had worked fine the previous evening of Monday 14th August. 
Windows displays the following dialog:
![2017-08-15_130557](https://user-images.githubusercontent.com/31060184/29350662-cb30669e-82a2-11e7-8ce0-f30be83dbb8c.png)
The logfile log.txt is created but has zero length.

**Comment by siegerx3** [comment]
Should be fixed with 1.0.7.0
