### ISSUE TITLE
Program not working reliably since v0.6.10.0 update.

### ISSUE THREAD

**Issue by dziban303** [jammin411/MatchmakingMonitor#32]
With the release of 0.6.10.0, and subsequently 0.6.10.1, Matchmaking Monitor functions properly about 20% of the time. 

Failure modes include a hang when trying to get stats, and another issue where the program fails to detect a game in progress.

**Comment by siegerx3** [comment]
What do you mean by hang? The program itself crashing or does it just take more time?
I can't do something about the response time of the wargaming API.

Failure of detecting the game should only be happening when the game doesn't create the tempArenaInfo.json file. It happened to me once and i know some ppl that had this issue. Sadly that's nothing i can fix.

Maybe you can give me some more details about the two things?
