### ISSUE TITLE
Display data in a single screen with no scrolling

### ISSUE THREAD

**Issue by baruch** [jammin411/MatchmakingMonitor#37]
I use a secondary screen and would like to have it show all data as scrolling down is inconvenient at game time. It would be nice if the font size and spacing was changed to allow the data to fit all in one screen.

**Comment by siegerx3** [comment]
So the smallest fontsize you can set in the options is still too big?
Maybe you should consider buying a new screen x)
No, seriously, did you try setting it to the smallest fontsize?

**Comment by baruch** [comment]
I failed to notice the font size setting, will try it later.

**Comment by baruch** [comment]
It worked. The spacing is too large and rather wasteful though.

Anyhow your attitude is not something I would like to endure.
