### ISSUE TITLE
Building solution

### ISSUE THREAD

**Issue by danielvistisen** [jammin411/MatchmakingMonitor#41]
When downloading the solution I can build it. Any chance you can make a guide how to?

Client solution can't find any references for Xceed or Ninject.

Nuget package restore dosn't seem to fix this.

Running VS 2017.

**Comment by siegerx3** [comment]
It happens when you download the zip somehow. When you use git, with git fetch etc it's working.
I have it running on 3 different machines like that.
As soon as i just download the zip it's having the error you describe.
