### ISSUE TITLE
Matchmaking Monitor no longer works for me

### ISSUE THREAD

**Issue by mike393** [jammin411/MatchmakingMonitor#45]
Jammin411!  I think I just subscribed to your youtube channel tonight when I was checking out the Kronstandt video.  I have a problem with matchmaking monitor not working for me and I am a power user who gets it through aslains mod pack..  I tried posting there but got no replies..   heres the post..  

>>>>I have been having trouble getting matchmaking monitor to work for me. I have used it in the mod pack since it was first available with no problems.  I recently moved to a new computer and it just won't work. I don't remember if it ever worked since the move to the new pc.  I have the program set to look in the right place and have done this many times before.  I now run windows 10 from windows 8 and the game now runs on my ssd  C: hard drive instead of the D: drive on the previous computer.  I added the exe to the firewall and even tried it with virus protection turned off.  I reinstalled it again with the latest Aslain's mod patch making sure I cleared out all the old mods and cache with a clean install of everything.   replays enabled, not enabled...nothing...  What gives?  I just have a empty matchmaking monitor screen...    Any help or further suggestion would be appreciated..

**Comment by siegerx3** [comment]
Hey, first of all, jammin411 is no longer working on this project :/
Good news, i am here!
Since this is more of a technical issues tracker, i suggest you join us at https://discord.gg/Tds7WBs.
And just to make sure, have you updated to the latest version? There have been some important changes in the recent versions.
