### ISSUE TITLE
Fit the layout  according to screen resolution? 

### ISSUE THREAD

**Issue by tautomer** [jammin411/MatchmakingMonitor#47]
On a 1600*900 screen, only 11 players can be shown in one page. You have always to scroll up or down to see the rest one. This one can be solved by smaller font in settings, but can the menu bar be hidden automatically so that there would be one more line for stats?

If you use a monitor vertically (no matter 1080\*1920 or 900\*1600), at least one column of the stats will be cut off. Is it possible to allow the blocks on the UI to resize or reshape so that any screen can always show the full information of all players?

**Comment by stewieoO** [comment]
Hey, i'm already planning on a complete rewrite of the application with electron+angular. 
So the UI will be HTML and WAY more responsive and dynamic. I can't tell you any date when i will have time for it. But it's definetly planned.

**Comment by tautomer** [comment]
@stewieoO That's really great! Hope to see a new mm monitor coming out. Thanks for your work!
