### ISSUE TITLE
[Feature] Show teams' overall winrate, besides their average

### ISSUE THREAD

**Issue by LtLazlow** [jammin411/MatchmakingMonitor#49]
I noticed that the method for calculating the average winrate for teams is simply adding up the the winrate of the players, who actually have stats for their current ship and don't have them hidden, and dividing it by the number of such players. This formula allows no way to distinguish between beginners who _may be down on luck_ or _had a lucky few first matches_, and people who are _chronic underachievers_ or _consistently play well_. Sure, you can look at the individual players, but an aggregate number might help more, when comparing some players to others (often in different types of ships), attempting to figure out which team stands a better chance.

So I'd be interested in **an additional metric**, which is _the sum total of all the victories of all the players_ in their respective current ships, _divided by the total number of battles of all the players_ in their respective current ships (expressed as a two-decimal percentage, of course). For lack of a better name, I'd call this their "overall winrate." My rationale is that the score would be weighed towards the winrates of people with high numbers of battles, giving somewhat of a picture about which team has players who are likely to carry a battle or be predictably weak.

**Comment by LtLazlow** [comment]
Not sure if this is what a different user was referring to in June, so I laid it out clearly.

**Comment by stewieoO** [comment]
@LtLazlow Was just going through all the open issues, and i think i implemented it like that in the new test version. But i'll check it again.
If you're not there yet and want to check it out: https://discord.gg/Tds7WBs
