### ISSUE TITLE
Replay folder changed

### ISSUE THREAD

**Issue by Supergoof** [jammin411/MatchmakingMonitor#53]
Hello and thanks for an awesome utility.

My matchmaking monitor recently stopped working and I noticed that the replay folder now contained subfolders with the WOWS version/build numbers and replays inside them. I presume that WG made this change silently but it seems that matchmaking monitor doesn't look in these new subfolders and thus don't work anymore. 

Regards Supergoof

**Comment by stewieoO** [comment]
Check out the new test version on my discord https://discord.gg/Tds7WBs.
It now works with all the different cases of replay locations!
