### ISSUE TITLE
v1.2.0.5issue

### ISSUE THREAD

**Issue by jason199506** [jammin411/MatchmakingMonitor#54]
tonight i just updated game client version to 0.7.11.1 and MMM version to 1.2.0.5
after i cover-replace install 1205 from 1204, it simply showed "not currently in battle" after several restart attempt
so i deleted the MMM folder altogether and re-extracted the 1205MMM fresh
it could start up, but my client is installed at C:/Games/World Of Warships not the default World_Of_Warships
and when i try to assign client path, MMM would just freeze/turn white/(Not Responding)

**Comment by Supergoof** [comment]
I have issues with 1.2.0.5 as well. Not only is it not working but the settings dialog and all other dialogs don't open.

**Comment by Lofarr** [comment]
WG changed the location of replay files, its now "C:\Games\World_of_Warships\replays\0.7.11.1"

**Comment by stewieoO** [comment]
If you still have problems, you can try out the new test version on my discord https://discord.gg/Tds7WBs!
It works with all those different folders where the current one has some problems with!
