### ISSUE TITLE
1.2.0.6 Issue

### ISSUE THREAD

**Issue by peppesbodega2** [jammin411/MatchmakingMonitor#55]
Same problem as with 1.2.0.5.
MM 1.2.0.6 doesnt work, doesnt fetch stats at all.
I play through Steam

**Comment by solarstoned** [comment]
I am having the same issue. as soon as i enabled replays MMM stopped working. I have cleaned and installed the program with different patches but nothing comes up.

**Comment by peppesbodega2** [comment]
He have still not fixed it but download 1.2.0.4 and it works for me.

**Comment by solarstoned** [comment]
thanks

**Comment by stewieoO** [comment]
If you still have problems, you can try out the new test version on my discord https://discord.gg/Tds7WBs!
