### ISSUE TITLE
1.2.0.6 - Doesnt work in Ranked Sprint

### ISSUE THREAD

**Issue by Nepturian** [jammin411/MatchmakingMonitor#56]
Fix it please!

26.12.2018 09:04:25 - Info - Match found
26.12.2018 09:04:25 - Info - Valid replay found. Fetching stats
26.12.2018 09:04:27 - Info - Less than 6 players with stats found. Something seems to be wrong

**Comment by jason199506** [comment]
similar issue, it said "found a battle but no stats, wrong region?"
im on NA, only ranked sprint it doesnt work, every other mode works fine

**Comment by 1-george-1** [comment]
identical issue as jason, "found a battle but no stats, wrong region?"
Perhaps WG is running ranked sprints on a separate server?

**Comment by Nepturian** [comment]
WG hasnt changed the stats API, think MMM program doesnt track this Sprint Seasons well anymore.

**Comment by stewieoO** [comment]
Check out the new test version on my discord https://discord.gg/Tds7WBs.
Working with ranked spring and some other new features!
