### ISSUE TITLE
[Feature]Overall Winrate

### ISSUE THREAD

**Issue by trillhouse** [jammin411/MatchmakingMonitor#57]
Literally all I need is someone's total account win rate. Per ship is useful, but it would be simpler and more useful if I just had total winrate.

**Comment by mrLobster** [comment]
This would make the usefulness of the application multiply by 5-15 times. 
Hmmm...it`s .NET/C#....ok, Ill put it in myself

**Comment by Corsair-I** [comment]
I disagree. You can always look at his total win rate by clicking on his name. What good is it to have the total win rate when you have the stats for the ship? Nobody is equally good or bad with a specific ship compared to the rest of the ship.

**Comment by stewieoO** [comment]
@trillhouse @mrLobster 
Check out the new test version in my discord https://discord.gg/Tds7WBs.
It has overall account stats and some other new stats :)
