### ISSUE TITLE
Dual Monitor confusion

### ISSUE THREAD

**Issue by freggo** [jammin411/MatchmakingMonitor#59]

**Comment by freggo** [comment]
I use 2 monitors side by side. 1920x1080 on the right, and 1920x1080 on the left.
World of Warships runs on the larger monitor, MM on the smaller one.
For some reason I had to switch the monitors for a while and told Win 10 about it so the cursor moves in the new direction. Works well with Win 10 and all my programs, just MM opens still on the "left side" of the large monitor. Only there is no monitor on the left of course and you can not move MM. I had to tell Win 10 I swapped monitors, move MM to the large monitor then reswap the monitors and move MM to the right.
Also, moving MM from the 1200 line monitor to the 1080 monitor xan make the top of the MM window disappear above the top edge of the monitor so you can not longer grab the window and move it.

Hope this is not to confusing :-)

P.S. would love it if MM had a CO-OP statistics option !!!

**Comment by stewieoO** [comment]
I'm guessing you can just open MMM and then press WinKey+Arrow (Left/Right) to move the Window back on the correct Screen. Once you close it on the correct screen the position should be saved correctly.

Next big version will have Coop stats :)
