### ISSUE TITLE
1.2.0.6 won't work with Steam version of WoWs?

### ISSUE THREAD

**Issue by illnar** [jammin411/MatchmakingMonitor#60]
I've been stuck on version 1.2.0.4 because versions 1.2.0.5 and current version 1.2.0.6 simply won't work.

It accepts my WoWs path (the same one that worked in 1.2.0.4), but every time I start a battle, nothing happens.

Is there anything I can do to get v1.2.0.6 to work with the Steam version?

Also, I know you don't support 1.2.0.4...but it's curious that that version isn't working with the new ranked season. It works with Randoms, Clan Battles but not the ranked season that started today. It recognizes a battle has started, but it gives the "no stats found, wrong region?" response.

Any help with any of the above would be GREATLY appreciated...thanks!

**Comment by stewieoO** [comment]
Hey!
Check out the channel #current-workaround on my discord  https://discord.gg/Tds7WBs.
As far as ranked goes, i am fetching the clan seasons from Wargaming. So far they don't return the new season. That's why ranked is not working atm.

**Comment by illnar** [comment]
Thanks for that. Is ranked working on the main 1.2.0.6 version (not your NoChecks version)? While I was in battle yesterday, some people in chat were letting us know who the good players were on the enemy team, so I assumed they were using MM.

**Comment by illnar** [comment]
Actually, I used your NoChecks version just now, and ranked stats are working, along with everything else. THANK YOU!
