### ISSUE TITLE
Won't pull from Wows-Numbers

### ISSUE THREAD

**Issue by hrcrawford** [jammin411/MatchmakingMonitor#62]
Today i find that MM won't sync the "standards" from EU server.  Every standard is "0" and everyone in display is purple.

**Comment by hrcrawford** [comment]
I notice they have a 5-second delay now to prevent DDOS.  Wonder if that's causing it.

**Comment by stewieoO** [comment]
It is. Already talked with the owner of the site. He's working on a solution to add an exception for the url that i'm calling (https://wows-numbers.com/personal/rating/expected/json/). Probably a new sub-domain for that.

In the meantime, if you want join my discord https://discord.gg/Tds7WBs to try the new version i'm working on. For that i'm caching the values on my server so it still works ;)
