### ISSUE TITLE
Doesn't work if your "replay" folder has sub folders for each version of the game

### ISSUE THREAD

**Issue by SlendyMcTendies** [jammin411/MatchmakingMonitor#64]
MMM doesn't recognize replay sub-folders. I use the Wargaming Center application for WOWS and it saves replays in sub-folders assigned to each version of the game (current version at time of writing is 0.8.9)

If possible, could you update the program so it searches the replay subfolders as well? I believe a Wildcard indicator would work in the directory search but I could be wrong.

Thank you for your time, hopefully bringing this to your attention was useful. This is my first time using the program and I haven't been able to get it to work.

**Comment by stewieoO** [comment]
Hey, i am aware of that problem. 
That's one of the reasons why i am completely rewriting the application.
At the moment it is in public testing.
If you want to check it out, you can join the discord https://discord.gg/3jEwHb.

At the moment that's the only place where you can download it, until i finished the new landing page :)

**Comment by Niederbayer** [comment]
Hi. 
I have the same problem. is it fixed so far
