### ISSUE TITLE
Found a battle but no stats. Wrong region?

### ISSUE THREAD

**Issue by Andris83** [jammin411/MatchmakingMonitor#74]
I just installed MatchmakingMonitor and went into a random battle, but all I get is this message:
Found a battle but no stats. Wrong region?

I'm certain I'm on EU, but nonetheless I tried every other region and got the same result. I have no idea what I could do to get it working.

**Comment by stewieoO** [comment]
Hey, unfortunately wargaming changed something in the latest update so this app is broken.
I do however have a new version in the final stages. If you didn't already find it through the website, you can join the discord []( https://discord.gg/Tds7WBs) and get it. Sorry for the inconvenience.
